-- AlterSequence
ALTER SEQUENCE "Branch_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "parentguardians_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "promotiondemotion_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "listofbanks" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bank" STRING NOT NULL,
    "country" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "listofbanks_pkey" PRIMARY KEY ("id")
);
