-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'SUPERADMIN');

-- CreateEnum
CREATE TYPE "Module" AS ENUM ('AUTH');

-- CreateEnum
CREATE TYPE "Acc" AS ENUM ('ACTIVE', 'SUSPENDED', 'PENDING', 'DELETED');

-- CreateEnum
CREATE TYPE "Yn" AS ENUM ('YES', 'NO');

-- CreateEnum
CREATE TYPE "accounttype" AS ENUM ('ASSET', 'CASH', 'CURRENT_ASSETS', 'EXPENSE', 'INCOME', 'EQUITY_RETAINED_EARNINGS', 'EQUITY_DOES_NOT_CLOSE', 'INVENTORY', 'OTHER_ASSET', 'COST_OF_SALES', 'FIXED_ASSET', 'OTHER_CURRENT_ASSET', 'ACCOUNTS_PAYABLE', 'ACCOUNTS_RECEIVABLE', 'ACCUMULATED_DEPRECIATION', 'LIABILITIES', 'OTHER_CURRENT_LIABILITIES', 'LONG_TERM_LIABILITIES', 'EQUITY');

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "firstname" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "othernames" STRING,
    "image" STRING,
    "email" STRING NOT NULL,
    "phone" STRING NOT NULL,
    "country" STRING,
    "state" STRING,
    "emailverified" TIMESTAMP(3),
    "address" STRING,
    "role" STRING NOT NULL DEFAULT 'MEMBER',
    "permissions" STRING,
    "userpermissions" STRING DEFAULT '',
    "password" STRING NOT NULL,
    "officeaddress" STRING,
    "image2" STRING,
    "gender" STRING,
    "occupation" STRING,
    "lga" STRING,
    "town" STRING,
    "maritalstatus" STRING,
    "spousename" STRING,
    "stateofresidence" STRING,
    "lgaofresidence" STRING,
    "nextofkinfullname" STRING,
    "nextofkinphone" STRING,
    "nextofkinrelationship" STRING,
    "nextofkinaddress" STRING,
    "nextofkinofficeaddress" STRING,
    "nextofkinoccupation" STRING,
    "dateofbirth" TIMESTAMP(3),
    "branch" INT4 DEFAULT 1,
    "registrationpoint" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdby" INT4 NOT NULL DEFAULT 0,
    "pin" STRING DEFAULT '',
    "level" INT4 DEFAULT 0,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Roles" (
    "role" STRING NOT NULL,
    "permissions" STRING,
    "description" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Roles_pkey" PRIMARY KEY ("role")
);

-- CreateTable
CREATE TABLE "Department" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "department" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "category" STRING DEFAULT 'STORE',
    "applyforsales" STRING DEFAULT 'JUST DEPARTMENT',
    "userid" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "lastupdated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Department_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DefineMember" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "lastupdated" TIMESTAMP(3),
    "addmember" STRING NOT NULL DEFAULT 'YES',
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "DefineMember_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" INT4 NOT NULL DEFAULT 1,
    "userid" INT4 NOT NULL,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Position" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "member" INT4 NOT NULL,
    "position" STRING NOT NULL,
    "userid" INT4 DEFAULT 0,
    "branch" INT4 DEFAULT 0,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Position_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Activity" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "activity" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "module" STRING NOT NULL DEFAULT 'AUTH',
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Activity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessiontoken" STRING NOT NULL,
    "userid" INT4 NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    "device" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" STRING NOT NULL,
    "token" STRING NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE'
);

-- CreateTable
CREATE TABLE "Branch" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "branch" STRING NOT NULL,
    "country" STRING,
    "state" STRING,
    "lga" STRING,
    "address" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastupdated" TIMESTAMP(3),
    "userid" INT4,
    "createdby" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Organisationsettings" (
    "id" INT4 NOT NULL DEFAULT 1,
    "company_name" STRING NOT NULL,
    "sms_sender_id" STRING NOT NULL,
    "phone" STRING NOT NULL DEFAULT '',
    "mobile" STRING NOT NULL DEFAULT '',
    "email" STRING NOT NULL,
    "address" STRING NOT NULL,
    "logo" STRING,
    "sms_charge" FLOAT8,
    "maintenace_charge" FLOAT8,
    "vat_rate_percent" FLOAT8 NOT NULL DEFAULT 0,
    "addition_savings_registration_charge" FLOAT8,
    "addition_loan_registration_charge" FLOAT8 DEFAULT 0,
    "allow_back_dated_transaction" STRING NOT NULL DEFAULT 'NO',
    "allow_future_transaction" STRING NOT NULL DEFAULT 'NO',
    "personal_account_overdrawn" BOOL NOT NULL DEFAULT false,
    "set_accounting_year_end" TIMESTAMP(3),
    "schedule_maintenace_charge" STRING NOT NULL DEFAULT 'NO',
    "sms_charge_members" STRING NOT NULL DEFAULT 'YES',
    "minimum_credit_amount" FLOAT8 NOT NULL DEFAULT 2000,
    "minimum_credit_amount_penalty" FLOAT8 NOT NULL DEFAULT 200,
    "personal_transaction_prefix" STRING,
    "loan_transaction_prefix" STRING,
    "rotary_transaction_prefix" STRING DEFAULT '',
    "gl_transaction_prefix" STRING,
    "savings_transaction_prefix" STRING,
    "property_transaction_prefix" STRING DEFAULT '',
    "savings_account_prefix" STRING,
    "personal_account_prefix" STRING NOT NULL DEFAULT 'DHF',
    "loan_account_prefix" STRING,
    "property_account_prefix" STRING DEFAULT '',
    "rotary_account_prefix" STRING DEFAULT '',
    "asset_account_prefix" STRING,
    "cash_account_prefix" STRING,
    "current_assets_account_prefix" STRING,
    "expense_account_prefix" STRING,
    "income_account_prefix" STRING,
    "equity_retained_earnings_account_prefix" STRING,
    "equity_does_not_close_prefix" STRING,
    "inventory_account_prefix" STRING,
    "other_asset_account_prefix" STRING,
    "cost_of_sales_account_prefix" STRING,
    "fixed_asset_account_prefix" STRING,
    "other_current_asset_account_prefix" STRING,
    "accounts_payable_account_prefix" STRING,
    "accounts_receivable_account_prefix" STRING,
    "accumulated_depreciation_account_prefix" STRING,
    "liabilities_account_prefix" STRING,
    "other_current_liabilities_account_prefix" STRING,
    "long_term_liabilities_account_prefix" STRING,
    "equity_account_prefix" STRING,
    "default_sms_charge_account" FLOAT8,
    "default_asset_account" FLOAT8,
    "default_cash_account" FLOAT8,
    "default_current_assets_account" FLOAT8,
    "default_expense_account" FLOAT8,
    "default_income_account" FLOAT8,
    "default_equity_retained_earnings_account" FLOAT8,
    "default_equity_does_not_close_account" FLOAT8,
    "default_inventory_account" FLOAT8,
    "default_other_asset_account" FLOAT8,
    "default_cost_of_sales_account" FLOAT8,
    "default_fixed_asset_account" FLOAT8,
    "default_other_current_asset_account" FLOAT8,
    "default_accounts_payable_account" FLOAT8,
    "default_accounts_receivable_account" FLOAT8,
    "default_accumulated_depreciation_account" FLOAT8,
    "default_liabilities_account" FLOAT8,
    "default_other_current_liabilities_account" FLOAT8,
    "default_long_term_liabilities_account" FLOAT8,
    "default_equity_account" FLOAT8,
    "default_tax_account" FLOAT8,
    "default_excess_account" FLOAT8,
    "default_allocation_account" FLOAT8 DEFAULT 0,
    "default_property_account" FLOAT8 DEFAULT 0,
    "default_rotary_account" FLOAT8 DEFAULT 0,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Organisationsettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Rejecttransactiondate" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rejectiondate" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "reason" STRING,

    CONSTRAINT "Rejecttransactiondate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Registrationpoint" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "registrationpoint" STRING NOT NULL,
    "description" STRING,
    "branch" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "datecreated" TIMESTAMP(3),
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Registrationpoint_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Task" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING,
    "priority" STRING NOT NULL,
    "assignedto" STRING,
    "branch" STRING NOT NULL,
    "startdate" TIMESTAMP(3) NOT NULL,
    "enddate" TIMESTAMP(3) NOT NULL,
    "taskstatus" STRING NOT NULL DEFAULT 'NOT STARTED',
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subtask" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "startdate" TIMESTAMP(3) NOT NULL,
    "enddate" TIMESTAMP(3) NOT NULL,
    "description" STRING,
    "taskstatus" STRING NOT NULL DEFAULT 'NOT STARTED',
    "createdby" STRING NOT NULL,
    "assignedto" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Subtask_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Cashierlimit" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cashier" INT4 NOT NULL,
    "depositlimit" FLOAT8 NOT NULL,
    "withdrawallimit" FLOAT8 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Cashierlimit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lastseen" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Lastseen_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Inventory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "itemid" INT4 NOT NULL,
    "itemname" STRING NOT NULL,
    "department" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "units" STRING NOT NULL,
    "cost" FLOAT8,
    "price" FLOAT8,
    "pricetwo" FLOAT8,
    "beginbalance" FLOAT8,
    "qty" FLOAT8,
    "minimumbalance" FLOAT8,
    "group" STRING,
    "applyto" STRING NOT NULL,
    "itemclass" STRING NOT NULL,
    "composite" STRING NOT NULL,
    "compositeid" INT4,
    "description" STRING,
    "imageone" STRING,
    "imagetwo" STRING,
    "imagethree" STRING,
    "sellingprice" FLOAT8,
    "reference" STRING,
    "transactiondate" STRING,
    "transactiondesc" STRING,
    "transactionref" STRING DEFAULT '',
    "reorderlevel" STRING DEFAULT '2',
    "issue" STRING,
    "issuetype" STRING,
    "supplier" STRING,
    "staff" STRING DEFAULT '',
    "returned" BOOL NOT NULL DEFAULT false,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Inventory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issue" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "issuetype" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "issue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Supplier" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "supplier" STRING NOT NULL,
    "contactperson" STRING NOT NULL,
    "contactpersonphone" STRING NOT NULL,
    "officeaddress" STRING,
    "nationality" STRING NOT NULL,
    "currency" STRING DEFAULT 'NGN',
    "state" STRING NOT NULL,
    "bank1" STRING,
    "accountnumber1" STRING,
    "bank2" STRING,
    "accountnumber2" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "savingsproduct" (
    "activationfee" FLOAT8,
    "allowdeposit" BOOL NOT NULL,
    "allowoverdrawn" BOOL NOT NULL,
    "allowwithdrawal" BOOL NOT NULL,
    "chargehere" BOOL NOT NULL DEFAULT false,
    "addmember" STRING NOT NULL DEFAULT 'NO',
    "compulsorydeposit" BOOL NOT NULL,
    "compulsorydepositdeficit" BOOL NOT NULL DEFAULT false,
    "compulsorydepositfrequency" STRING,
    "compulsorydepositfrequencyamount" FLOAT8,
    "compulsorydepositfrequencyskip" INT4,
    "compulsorydepositpenalty" FLOAT8,
    "compulsorydepositpenaltyfallbackfrom" STRING,
    "compulsorydepositpenaltyfrom" STRING,
    "compulsorydepositpenaltytype" STRING,
    "compulsorydepositspillover" BOOL NOT NULL,
    "compulsorydeposittype" STRING,
    "currency" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "depositcharge" FLOAT8,
    "depositechargetype" STRING DEFAULT 'PERCENTAGE',
    "eligibilityaccountage" INT4,
    "eligibilityminbalance" FLOAT8,
    "eligibilitymincredit" FLOAT8,
    "eligibilitymindebit" FLOAT8,
    "eligibilityminimumclosedaccounts" INT4,
    "eligibilityminimumloan" FLOAT8,
    "eligibilityproduct" INT4 DEFAULT 0,
    "eligibilityproductcategory" STRING,
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "maxbalance" FLOAT8,
    "membership" STRING DEFAULT '',
    "minimumaccountbalance" FLOAT8,
    "productname" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "updatedat" TIMESTAMP(3),
    "useraccount" INT4 DEFAULT 1,
    "withdrawalcharges" FLOAT8,
    "withdrawalchargeinterval" STRING,
    "withdrawalchargetype" STRING,
    "withdrawalcontrol" BOOL DEFAULT false,
    "withdrawalcontrolamount" FLOAT8 DEFAULT 0,
    "withdrawalcontrolsize" STRING,
    "withdrawalcontroltype" STRING,
    "withdrawalcontrolwindow" STRING,
    "withdrawallimit" FLOAT8,
    "withdrawallimittype" STRING,

    CONSTRAINT "savingsproduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Interest" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "interestname" STRING NOT NULL,
    "interestmethod" STRING NOT NULL,
    "interesteligibilityaccountage" INT4 NOT NULL DEFAULT 0,
    "interesteligibilitybalance" FLOAT8 NOT NULL DEFAULT 0,
    "interestamount" FLOAT8 NOT NULL,
    "interesttype" STRING NOT NULL,
    "interestfrequency" STRING NOT NULL,
    "interestfrequencynumber" INT4,
    "interestfrequencyskip" INT4,
    "interestgoforapproval" BOOL NOT NULL DEFAULT false,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Interest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "frequencyoverride" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "compulsorydepositfrequency" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "frequencyoverride_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Deduction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "deductionname" STRING NOT NULL,
    "deductioneligibilityaccountage" INT4 NOT NULL DEFAULT 0,
    "deductioneligibilitybalance" FLOAT8 NOT NULL DEFAULT 0,
    "deductionamount" FLOAT8 NOT NULL,
    "deductiontype" STRING NOT NULL,
    "deductionmethod" STRING NOT NULL,
    "deductionfrequency" STRING NOT NULL,
    "deductionfrequencynumber" INT4,
    "deductionfrequencyskip" INT4,
    "deductiongoforapproval" BOOL NOT NULL DEFAULT false,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Deduction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "savings" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "savingsproductid" INT4 NOT NULL,
    "accountnumber" INT4 NOT NULL,
    "userid" INT4 NOT NULL,
    "amount" FLOAT8 NOT NULL,
    "member" INT4 DEFAULT 0,
    "branch" INT4 NOT NULL,
    "registrationpoint" INT4,
    "registrationcharge" FLOAT8 NOT NULL,
    "registrationdate" TIMESTAMP(3) NOT NULL,
    "registrationdesc" STRING,
    "bankname1" STRING,
    "bankaccountname1" STRING,
    "bankaccountnumber1" INT4,
    "bankname2" STRING,
    "bankaccountname2" STRING,
    "bankaccountnumber2" STRING,
    "accountofficer" STRING,
    "sms" BOOL,
    "whatsapp" BOOL,
    "email" BOOL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,
    "reason" STRING DEFAULT '',

    CONSTRAINT "savings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "userid" INT4 NOT NULL,
    "currency" STRING NOT NULL,
    "credit" FLOAT8 NOT NULL DEFAULT 0,
    "debit" FLOAT8 NOT NULL DEFAULT 0,
    "description" STRING,
    "image" STRING,
    "branch" INT4,
    "registrationpoint" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvedby" INT4,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "updateddated" TIMESTAMP(3),
    "transactiondate" TIMESTAMP(3),
    "transactiondesc" STRING,
    "transactionref" STRING DEFAULT '',
    "cashref" STRING DEFAULT '',
    "updatedby" INT4,
    "ttype" STRING,
    "tfrom" STRING,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "valuedate" TIMESTAMP(3),
    "reference" STRING,
    "whichaccount" STRING,
    "voucher" STRING DEFAULT '',
    "tax" BOOL DEFAULT false,

    CONSTRAINT "transaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "banktransaction" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "userid" INT4 NOT NULL DEFAULT 0,
    "description" STRING,
    "debit" INT4,
    "credit" INT4,
    "ttype" STRING,
    "tfrom" STRING,
    "createdby" INT4 NOT NULL DEFAULT 0,
    "valuedate" TIMESTAMP(3),
    "reference" STRING,
    "transactiondate" TIMESTAMP(3),
    "transactiondesc" STRING,
    "transactionref" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "whichaccount" STRING,
    "rawdata" STRING,

    CONSTRAINT "banktransaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Accounts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "groupname" STRING,
    "accounttype" STRING,
    "description" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loanfee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "feename" STRING NOT NULL,
    "feemethod" STRING NOT NULL,
    "chargesbasedon" STRING NOT NULL,
    "chargeamount" FLOAT8,
    "chargetype" STRING,
    "glaccount" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "loanfee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loanproduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "productname" STRING NOT NULL,
    "description" STRING,
    "registrationcharge" FLOAT8,
    "repaymentsettings" STRING NOT NULL,
    "repaymentfrequency" STRING,
    "numberofrepayments" INT4,
    "duration" INT4,
    "durationcategory" STRING,
    "interestmethod" STRING NOT NULL,
    "interestrate" FLOAT8 NOT NULL,
    "interestratetype" STRING,
    "defaultpenaltyid" INT4,
    "seperateinterest" BOOL DEFAULT false,
    "useraccount" INT4 DEFAULT 1,
    "eligibilityproductcategory" STRING,
    "eligibilityproduct" INT4 DEFAULT 0,
    "eligibilityaccountage" INT4,
    "eligibilityminbalance" FLOAT8,
    "eligibilitymincredit" FLOAT8,
    "eligibilitymindebit" FLOAT8,
    "eligibilityminimumloan" FLOAT8,
    "eligibilityminimumclosedaccounts" INT4,
    "eligibilitytype" STRING,
    "maximumloan" FLOAT8,
    "minimumloan" FLOAT8,
    "membership" STRING DEFAULT '',
    "currency" STRING,
    "excludebranch" STRING,
    "productofficer" STRING,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "member" INT4 DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "loanproduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loanaccounts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "loanproduct" INT4 DEFAULT 0,
    "accountnumber" STRING,
    "userid" INT4 NOT NULL,
    "branch" INT4 NOT NULL,
    "registrationpoint" INT4,
    "registrationcharge" FLOAT8,
    "registrationdate" TIMESTAMP(3) NOT NULL,
    "registrationdesc" STRING,
    "loanamount" FLOAT8 NOT NULL,
    "bankname1" STRING,
    "bankaccountname1" STRING,
    "bankaccountnumber1" STRING,
    "bankname2" STRING,
    "bankaccountname2" STRING,
    "bankaccountnumber2" STRING,
    "accountofficer" STRING,
    "repaymentfrequency" STRING,
    "numberofrepayments" INT4,
    "duration" INT4,
    "durationcategory" STRING,
    "interestmethod" STRING NOT NULL,
    "interestrate" FLOAT8 NOT NULL,
    "interestratetype" STRING,
    "defaultpenaltyid" INT4,
    "seperateinterest" BOOL DEFAULT false,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "dateclosed" TIMESTAMP(3),
    "closeamount" FLOAT8,
    "createdby" INT4 NOT NULL,
    "member" INT4 DEFAULT 0,
    "disbursementref" STRING DEFAULT '',
    "disbursementdate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "loanaccounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loanpaymentschedule" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "scheduledpaymentdate" TIMESTAMP(3) NOT NULL,
    "gracepaymentdate" TIMESTAMP(3),
    "scheduleamount" FLOAT8 NOT NULL,
    "interestamount" FLOAT8 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "createdby" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL,
    "reference" STRING,

    CONSTRAINT "loanpaymentschedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "collateral" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "documenttitle" STRING NOT NULL,
    "documentnumber" STRING NOT NULL,
    "description" STRING NOT NULL,
    "docposition" STRING NOT NULL DEFAULT 'ISSUED',
    "documentexpiration" TIMESTAMP(3),
    "worth" FLOAT8 NOT NULL,
    "file1" STRING,
    "file2" STRING,
    "file3" STRING,
    "file4" STRING,
    "file5" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "collateral_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Service" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "serviceid" UUID NOT NULL DEFAULT gen_random_uuid(),
    "supplier" INT4 NOT NULL,
    "staff" INT4,
    "servicetype" STRING NOT NULL,
    "description" STRING NOT NULL,
    "otherdetails" STRING DEFAULT '',
    "amount" FLOAT8,
    "currency" STRING DEFAULT 'NGN',
    "amountfrom" FLOAT8,
    "amountto" FLOAT8,
    "servicestartdate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "serviceenddate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "branch" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "issue" STRING,
    "reference" STRING NOT NULL DEFAULT '',
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "otp" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "otp" STRING NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "otp_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Property" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "itemid" INT4 NOT NULL,
    "itemname" STRING NOT NULL,
    "department" STRING NOT NULL,
    "branch" INT4 NOT NULL,
    "units" STRING NOT NULL,
    "cost" FLOAT8,
    "price" FLOAT8,
    "pricetwo" FLOAT8,
    "beginbalance" FLOAT8,
    "qty" FLOAT8,
    "minimumbalance" FLOAT8,
    "group" STRING,
    "applyto" STRING NOT NULL,
    "itemclass" STRING NOT NULL,
    "composite" STRING NOT NULL,
    "compositeid" INT4,
    "description" STRING,
    "imageone" STRING,
    "imagetwo" STRING,
    "imagethree" STRING,
    "sellingprice" FLOAT8,
    "reference" STRING,
    "transactiondate" STRING,
    "transactiondesc" STRING,
    "transactionref" STRING DEFAULT '',
    "reorderlevel" STRING DEFAULT '2',
    "issue" STRING,
    "issuetype" STRING,
    "supplier" STRING,
    "staff" STRING DEFAULT '',
    "returned" BOOL NOT NULL DEFAULT false,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL,
    "createdby" INT4 NOT NULL,

    CONSTRAINT "Property_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "compositedetails" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "compositeid" INT4 NOT NULL,
    "itemid" INT4 NOT NULL,
    "qty" INT4 NOT NULL,
    "createdby" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "compositedetails_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "categorytimeline" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "valuefrom" INT4 NOT NULL,
    "valueto" INT4 NOT NULL,
    "numberofdays" INT4 NOT NULL,
    "createdby" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "categorytimeline_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "propertyproduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product" STRING NOT NULL,
    "member" STRING,
    "useraccount" INT4 NOT NULL DEFAULT 1,
    "registrationcharge" STRING,
    "createdby" INT4 NOT NULL,
    "description" STRING DEFAULT '',
    "currency" STRING NOT NULL DEFAULT 'NGN',
    "productofficer" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "propertyproduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "propertyaccount" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "productid" INT4 NOT NULL,
    "accountnumber" STRING NOT NULL,
    "userid" INT4 NOT NULL,
    "membershipid" INT4,
    "registrationcharge" INT4 NOT NULL,
    "registrationdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "registrationpoint" STRING,
    "accountofficer" INT4,
    "repaymentfrequency" STRING,
    "numberofrepayments" INT4,
    "percentagedelivery" INT4,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "propertyaccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "propertyitems" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "itemid" INT4 NOT NULL,
    "qty" INT4 NOT NULL,
    "price" INT4 NOT NULL,
    "userid" INT4 NOT NULL,
    "delivered" STRING NOT NULL DEFAULT 'NO',
    "deliverystatus" STRING NOT NULL DEFAULT 'NOT STARTED',
    "deliveryrequested" STRING NOT NULL DEFAULT 'NO',
    "deliveryrequestdate" TIMESTAMP(3),
    "readyfordelivery" STRING NOT NULL DEFAULT 'NO',
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "propertyitems_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "propertyinstallments" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "amount" FLOAT8 NOT NULL DEFAULT 0,
    "duedate" TIMESTAMP(3) NOT NULL,
    "delivered" STRING NOT NULL DEFAULT 'NO',
    "userid" INT4 NOT NULL,
    "transactionref" STRING DEFAULT '',
    "description" STRING DEFAULT '',
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "propertyinstallments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rotaryProduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product" STRING NOT NULL,
    "member" STRING,
    "useraccount" INT4 NOT NULL DEFAULT 1,
    "registrationcharge" STRING,
    "createdby" INT4 NOT NULL,
    "description" STRING DEFAULT '',
    "currency" STRING NOT NULL DEFAULT 'NGN',
    "productofficer" INT4,
    "poolnumber" STRING NOT NULL,
    "rotaryschedule" STRING DEFAULT 'PRODUCT',
    "frequency" STRING,
    "frequencynumber" INT4,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "rotaryProduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rotaryaccount" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" STRING NOT NULL,
    "userid" INT4 NOT NULL DEFAULT 0,
    "branch" INT4 NOT NULL DEFAULT 0,
    "registrationcharge" FLOAT8 DEFAULT 0,
    "registrationdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "registrationpoint" INT4 DEFAULT 0,
    "registrationdesc" STRING DEFAULT '',
    "member" INT4 NOT NULL DEFAULT 0,
    "productid" INT4 NOT NULL,
    "amount" FLOAT8 NOT NULL,
    "frequency" STRING,
    "frequencynumber" INT4,
    "autorunnew" STRING NOT NULL DEFAULT 'YES',
    "createdby" INT4 NOT NULL DEFAULT 0,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateupdated" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "takeout" INT4 NOT NULL DEFAULT 0,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "rotaryaccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rotaryschedule" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "accountnumber" INT4 NOT NULL,
    "amount" FLOAT8 NOT NULL,
    "duedate" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "currentschedule" STRING NOT NULL DEFAULT 'true',
    "createdby" INT4 NOT NULL,
    "payout" STRING NOT NULL DEFAULT 'NO',
    "payoutref" STRING DEFAULT '',
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "rotaryschedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "level" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "level" STRING NOT NULL,
    "description" STRING,
    "basicsalary" FLOAT8,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "level_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "allowances" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "level" INT4 NOT NULL,
    "allowance" FLOAT8 NOT NULL,
    "allowancetype" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "allowances_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deductions" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "level" INT4 NOT NULL,
    "deduction" FLOAT8 NOT NULL,
    "deductiontype" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "deductions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "guarantor" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "guarantorname" STRING NOT NULL,
    "guarantorofficeaddress" STRING NOT NULL,
    "guarantorresidentialaddress" STRING NOT NULL,
    "guarantoroccupation" STRING NOT NULL,
    "guarantorphone" STRING NOT NULL,
    "imageone" STRING,
    "imagetwo" STRING,
    "yearsknown" INT4 NOT NULL,
    "createdby" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "guarantor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employmentrecord" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "employer" STRING NOT NULL,
    "position" STRING NOT NULL,
    "years" INT4 NOT NULL,
    "reasonofleaving" STRING NOT NULL,
    "doc" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "employmentrecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "referee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "refereename" STRING NOT NULL,
    "refereeofficeaddress" STRING NOT NULL,
    "refereeresidentialaddress" STRING NOT NULL,
    "refereeoccupation" STRING NOT NULL,
    "refereephone" STRING NOT NULL,
    "refereeyearsknown" INT4 NOT NULL,
    "relationship" STRING NOT NULL,
    "imageone" STRING,
    "imagetwo" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "referee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "qualification" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "institution" STRING NOT NULL,
    "certificationdate" TIMESTAMP(3) NOT NULL,
    "imageone" STRING,
    "imagetwo" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "qualification" STRING NOT NULL,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "qualification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "parentguardians" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "parentonename" STRING NOT NULL,
    "parentoneoccupation" STRING NOT NULL,
    "parentonestate" STRING NOT NULL,
    "parentoneofficeaddress" STRING NOT NULL,
    "parentonephone" STRING NOT NULL,
    "parenttwoname" STRING NOT NULL,
    "parenttwooccupation" STRING NOT NULL,
    "parenttwoofficeaddress" STRING NOT NULL,
    "parenttwostate" STRING NOT NULL,
    "parenttwophone" STRING NOT NULL,
    "parentoneimage" STRING,
    "parenttwoimage" STRING,
    "homeaddress" STRING NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "parentguardians_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "query" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "query" STRING NOT NULL,
    "imageone" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "query_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "promotiondemotion" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "type" STRING NOT NULL,
    "level" INT4 NOT NULL,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "promotiondemotion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "terminationresignation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "type" STRING NOT NULL,
    "image" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "terminationresignation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "suspension" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "image" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "suspension_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "leave" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "startdate" TIMESTAMP(3) NOT NULL,
    "enddate" TIMESTAMP(3) NOT NULL,
    "image" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "leave_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "warning" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "image" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "warning_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "monitoringevaluation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userid" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "image" STRING,
    "dateadded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdby" INT4 NOT NULL,
    "status" STRING NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "monitoringevaluation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");

-- CreateIndex
CREATE UNIQUE INDEX "Roles_role_key" ON "Roles"("role");

-- CreateIndex
CREATE UNIQUE INDEX "DefineMember_member_key" ON "DefineMember"("member");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessiontoken_key" ON "Session"("sessiontoken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- CreateIndex
CREATE UNIQUE INDEX "Branch_branch_key" ON "Branch"("branch");

-- CreateIndex
CREATE UNIQUE INDEX "issue_issuetype_key" ON "issue"("issuetype");

-- CreateIndex
CREATE UNIQUE INDEX "Supplier_supplier_key" ON "Supplier"("supplier");

-- CreateIndex
CREATE UNIQUE INDEX "loanfee_feename_key" ON "loanfee"("feename");

-- CreateIndex
CREATE UNIQUE INDEX "loanproduct_productname_key" ON "loanproduct"("productname");

-- CreateIndex
CREATE UNIQUE INDEX "propertyproduct_product_key" ON "propertyproduct"("product");

-- CreateIndex
CREATE UNIQUE INDEX "rotaryProduct_product_key" ON "rotaryProduct"("product");

-- AddForeignKey
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_userid_fkey" FOREIGN KEY ("userid") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userid_fkey" FOREIGN KEY ("userid") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Interest" ADD CONSTRAINT "Interest_savingsproductid_fkey" FOREIGN KEY ("savingsproductid") REFERENCES "savingsproduct"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Deduction" ADD CONSTRAINT "Deduction_savingsproductid_fkey" FOREIGN KEY ("savingsproductid") REFERENCES "savingsproduct"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
